MODEL:
  NUM_CLASSES: 2
DATASETS:
  TRAIN: ("abandon_buildings", )
  TEST: ("abandon_buildings_test", )
OUTPUT_DIR: 'outputs/abandon_buildings_ite_24k'
SOLVER:
  MAX_ITER: 24000
  LR_STEPS: [8000, 10000]
