MODEL:
  NUM_CLASSES: 2
DATASETS:
  TRAIN: ("abandon_buildings", )
  TEST: ("abandon_buildings_test", )
OUTPUT_DIR: 'outputs/abandon_buildings'
SOLVER:
  MAX_ITER: 72000
  LR_STEPS: [48000, 60000]
