# 从头开始0.5阈值训练3600张图片左右，120k次

MODEL:
  NUM_CLASSES: 3
DATASETS:
  TRAIN: ("abbd", )
  TEST: ("abbd_test", )
OUTPUT_DIR: 'outputs/abbd_iter3'
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]

