MODEL:
  NUM_CLASSES: 3
  BACKBONE:
    NAME: 'efficient_net-b3'
    OUT_CHANNELS: (48, 136, 384, 256, 256, 256)
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("abbd", )
  TEST: ("abbd_test", )
OUTPUT_DIR: 'outputs/abbd_efficient_net_120k'
SOLVER:
  MAX_ITER: 200000
  LR_STEPS: [135000, 165000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-3
