# 从头开始以0.65的阈值训练3850张图片左右，120k次

MODEL:
  NUM_CLASSES: 3
  THRESHOLD: 0.65
DATASETS:
  TRAIN: ("abbd", )
  TEST: ("abbd_test", )
OUTPUT_DIR: 'outputs/abbd_iter5'
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]

